import "./styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Be_Vietnam_Pro } from "next/font/google";

export const be_vietnam_pro = Be_Vietnam_Pro({
  variable: "--vietnam-pro",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={be_vietnam_pro.variable}>{children}</body>
    </html>
  );
}
